### ISSUE TITLE
Email not working.

### ISSUE THREAD

**Issue by zcaudate** [sordina/sordina.github.io#13]
@sordina: Lyndon, your email and domain is not working

**Comment by sordina** [comment]
Oh cool yeah that would be interesting, maybe we could have a little catch
up about it some time?

**Comment by zcaudate** [comment]
awesome. if you're on WhatsApp, my number is +8618088273090. and email is zcaudate@outlook.com I'll delete this once sent. 

btw... do you know who @jhcloos is? This account is watching a lot of projects.
